### PR TITLE
chore: always return error when got error

### PR DESCRIPTION
**Pull request by detailyang**
Hello.

We have known there are many bad cases which forget to return the error value when got the error in PR #49. So I wrote small workaround  but effective  go AST visitor script to find the pattern (not always right) as the following:

```
if cond {
    log.Error(...)
}
```
You can find these bad cases by running the command

```bash
curl -o /tmp/finderr.go https://gist.githubusercontent.com/detailyang/3c8fc54e1a84f8e547b3a5583845e5dc/raw/5d60ea3f1552d08170c849cb8b2aff7a18baab77/finderr.go 2>/dev/null; go run /tmp/finderr.go $GOPATH/src/github.com/copernet/copernicus
```

### CODE REVIEW

**Comment by detailyang** [comment]
It looks like the master branch had been broken.  It cannot be repoduced on Mac OSX:(

**Comment by detailyang** [comment]
It's interesting. The tests cannot be passed at Linux but Mac OSX is okay. I will continue deeply dig ha.

**Comment by detailyang** [comment]
Fixed because of secp256k1-go

**Comment by fffreedom** [comment]
Great! It's really should be a habit!

**Pull request merged**
